### ISSUE TITLE
fix for hexo 3

### ISSUE THREAD

**Issue by dai-shi** [leecrossley/hexo-generator-cname#1]
Here is what I did. Hope it helps.

```
hexo.extend.generator.register(function(locals) {
  return {
    path: 'CNAME',
    data: this.config.url.replace('http://', '')
  };
});
```

Might be better to support 'https://'

**Comment by leecrossley** [comment]
Thanks, I have made your changes. You can't use a custom domain name with GitHub pages and HTTPS.

**Comment by dai-shi** [comment]
I see. Thanks for your quick fix.
